### ISSUE TITLE
Missing go.sh

### ISSUE THREAD

**Issue by kitlith** [ericchu94/hsapp#1]
The README says that in order to run on windows, one may have to rename `go.sh` to be `go.bat`. However, the repository in its current state has no `go.sh`. Is this a leftover from an earlier state in development?

**Comment by ericchu94** [comment]
Nah, it does a git clone on d0k3's Universal Inject Generator. The go.sh is in there

https://github.com/ericchu94/hsapp/blob/60d0805f2a13de3cf601397d4e786a38e8147929/hsapp.js#L57

**Comment by kitlith** [comment]
Yup, realized that when I was looking around more. Whoops.

As an aside (not related to this nonexistant issue), Why not use the latest version of Universal Inject Generator instead of hardcoding the commit ID? Worried that it'll break in the future?

**Comment by ericchu94** [comment]
Yes basically. I've had a couple bad experiences with Universal Inject Generator breaking due to latest commit being buggy. I pinned the commit just in case.

I now realize that I probably should have used a git submodule. Oh well

**Comment by kitlith** [comment]
Well, that can be fixed... would make the actual app simpler.

**Comment by ericchu94** [comment]
You can send me a pull request :)
